version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      provider-group:
        patterns:
          - "azurerm"
        update-types:
          - "minor"
          - "patch"
      provider-major-upgrade:
        patterns:
          - "azurerm"
        update-types:
          - "major"
