version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-patch-providers:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # major-providers:
      #   patterns:
      #     - "*"
      #   update-types:
      #     - "major"
