version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      provider-minor-patch:
        patterns:
          - "azurerm"
          - "azurecaf"
          - "random"
        update-types:
          - "minor"
          - "patch"

      provider-major-upgrade:
        patterns:
          - "azurerm"
          - "azurecaf"
          - "random"
        update-types:
          - "major"
