# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-providers:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
